import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/api/auth.service';

@Component({ selector: 'app-profile', standalone: true, imports: [CommonModule, ReactiveFormsModule], templateUrl: './profile.component.html', styleUrl: './profile.component.css' })
export class ProfileComponent implements OnInit {
  busy = false; notice = ''; preview = ''; aadhaarFileName = ''; readonly form;
  constructor(fb: FormBuilder, public readonly auth: AuthService, private readonly router: Router) { this.form = fb.nonNullable.group({ name: ['', Validators.required], phoneNumber: ['', [Validators.required, Validators.pattern(/^[0-9+() -]{7,20}$/)]], age: [18, [Validators.required, Validators.min(18)]], gender: ['', Validators.required], location: ['', Validators.required], height: [0, [Validators.required, Validators.min(1)]], weight: [0, [Validators.required, Validators.min(1)]], education: ['', Validators.required], experience: ['', Validators.required], picture: ['', Validators.required], aadhaarDocument: [''] }); }
  ngOnInit() { if (!this.auth.state.value) { this.router.navigateByUrl('/auth'); return; } this.auth.profile().subscribe({ next: p => { this.form.patchValue(p); this.preview = p.picture ?? ''; }, error: () => this.router.navigateByUrl('/auth') }); }
  phoneInput(event: Event) { const input = event.target as HTMLInputElement; const cleaned = input.value.replace(/[^0-9+() -]/g, ''); if (cleaned !== input.value) { input.value = cleaned; this.form.controls.phoneNumber.setValue(cleaned); } }
  picture(event: Event) { const f = (event.target as HTMLInputElement).files?.[0]; if (!f || !f.type.startsWith('image/')) { this.notice = 'Choose a valid image file.'; return; } const r = new FileReader(); r.onload = () => { this.preview = String(r.result); this.form.controls.picture.setValue(this.preview); this.form.controls.picture.markAsTouched(); }; r.readAsDataURL(f); }
  aadhaar(event: Event) { const f = (event.target as HTMLInputElement).files?.[0]; if (!f || (!f.type.startsWith('image/') && f.type !== 'application/pdf') || f.size > 5_000_000) { this.notice = 'Upload an Aadhaar image or PDF under 5 MB.'; return; } const r = new FileReader(); r.onload = () => { this.aadhaarFileName = f.name; this.form.controls.aadhaarDocument.setValue(String(r.result)); this.form.controls.aadhaarDocument.markAsTouched(); }; r.readAsDataURL(f); }
  isInvalid(field: string) { const control = this.form.get(field); return !!control && control.invalid && control.touched; }
  fieldError(field: string) { const control = this.form.get(field); if (!control?.invalid || !control.touched) return ''; const label = ({ name: 'Full name', phoneNumber: 'Phone number', age: 'Age', gender: 'Gender', location: 'Location', height: 'Height', weight: 'Weight', education: 'Education', experience: 'Experience', picture: 'Profile picture', aadhaarDocument: 'Aadhaar card document' } as Record<string, string>)[field]; if (control.hasError('pattern')) return 'Use only numbers and phone symbols (+, -, spaces, parentheses).'; if (control.hasError('min')) return field === 'age' ? 'You must be at least 18 years old.' : `${label} must be greater than zero.`; return `${label} is required.`; }
  save() { if (this.form.invalid) { this.form.markAllAsTouched(); return; } this.busy = true; this.notice = ''; this.auth.saveProfile(this.form.getRawValue()).subscribe({ next: () => { this.busy = false; this.router.navigateByUrl('/'); }, error: e => { this.busy = false; this.notice = e.error?.message ?? e.error?.errors?.[0]?.defaultMessage ?? 'Could not save your profile.'; } }); }
}
