import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { AbstractControl, FormBuilder, ReactiveFormsModule, ValidationErrors, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/api/auth.service';

@Component({ selector: 'app-auth', standalone: true, imports: [CommonModule, ReactiveFormsModule, RouterLink], templateUrl: './auth.component.html', styleUrl: './auth.component.css' })
export class AuthComponent {
  mode: 'signin' | 'signup' | 'otp' | 'forgot' | 'reset' = 'signin'; notice = ''; busy = ''; pendingEmail = ''; showTerms = false;
  readonly signInForm; readonly signUpForm; readonly otpForm; readonly forgotForm; readonly resetForm;
  constructor(fb: FormBuilder, private readonly auth: AuthService, private readonly router: Router) {
    this.signInForm = fb.nonNullable.group({ email: ['', [Validators.required, Validators.email]], password: ['', Validators.required] });
    this.signUpForm = fb.nonNullable.group({ email: ['', [Validators.required, Validators.email]], password: ['', [Validators.required, Validators.minLength(8)]], confirmPassword: ['', Validators.required], termsAccepted: [false, Validators.requiredTrue] }, { validators: passwordsMatch });
    this.otpForm = fb.nonNullable.group({ otp: ['', [Validators.required, Validators.pattern(/^\d{6}$/)]] });
    this.forgotForm = fb.nonNullable.group({ email: ['', [Validators.required, Validators.email]] });
    this.resetForm = fb.nonNullable.group({ otp: ['', [Validators.required, Validators.pattern(/^\d{6}$/)]], password: ['', [Validators.required, Validators.minLength(8)]], confirmPassword: ['', Validators.required] }, { validators: passwordsMatch });
  }
  submitSignIn() { if (this.signInForm.invalid) return this.signInForm.markAllAsTouched(); this.busy = 'signin'; this.notice = ''; const v = this.signInForm.getRawValue(); this.auth.signIn(v.email, v.password).subscribe({ next: r => { this.busy = ''; if (r.token) this.router.navigateByUrl(r.profileComplete ? '/' : '/profile'); else { this.pendingEmail = r.email; this.mode = 'otp'; } }, error: e => { this.busy = ''; if (e.error?.message === 'Account not found.') { this.signUpForm.controls.email.setValue(v.email); this.mode = 'signup'; this.notice = 'No account was found for that email. Create one to continue.'; } else this.notice = e.error?.message ?? 'Unable to sign in.'; } }); }
  submitSignUp() { if (this.signUpForm.invalid) { this.signUpForm.markAllAsTouched(); if (this.signUpForm.controls.password.hasError('minlength')) this.notice = 'Password must be at least 8 characters.'; else if (this.signUpForm.hasError('passwordMismatch')) this.notice = 'Passwords do not match.'; else if (this.signUpForm.controls.termsAccepted.invalid) this.notice = 'Please accept the Terms & Conditions to continue.'; else this.notice = 'Please complete the highlighted fields.'; return; } this.busy = 'signup'; this.notice = ''; const { email, password, termsAccepted } = this.signUpForm.getRawValue(); this.auth.signUp({ email, password, termsAccepted }).subscribe({ next: r => { this.busy = ''; this.pendingEmail = r.email; this.mode = 'otp'; }, error: e => { this.busy = ''; this.notice = e.error?.message ?? 'Unable to create account.'; } }); }
  verify() { if (this.otpForm.invalid) return this.otpForm.markAllAsTouched(); this.busy = 'otp'; this.auth.verifyOtp(this.pendingEmail, this.otpForm.getRawValue().otp).subscribe({ next: () => { this.busy = ''; this.router.navigateByUrl('/profile'); }, error: e => { this.busy = ''; this.notice = e.error?.message ?? 'Unable to verify OTP.'; } }); }
  forgotPassword() { if (this.forgotForm.invalid) return this.forgotForm.markAllAsTouched(); this.busy = 'forgot'; this.notice = ''; const email = this.forgotForm.controls.email.value; this.auth.forgotPassword(email).subscribe({ next: response => { this.busy = ''; this.pendingEmail = email; this.notice = response.message; this.mode = 'reset'; }, error: e => { this.busy = ''; this.notice = e.error?.message ?? 'Unable to send a password reset code.'; } }); }
  resetPassword() { if (this.resetForm.invalid) { this.resetForm.markAllAsTouched(); this.notice = this.resetForm.hasError('passwordMismatch') ? 'Passwords do not match.' : 'Enter a valid 6-digit code and a password of at least 8 characters.'; return; } this.busy = 'reset'; const { otp, password } = this.resetForm.getRawValue(); this.auth.resetPassword(this.pendingEmail, otp, password).subscribe({ next: response => { this.busy = ''; this.notice = response.message; this.mode = 'signin'; this.signInForm.controls.email.setValue(this.pendingEmail); }, error: e => { this.busy = ''; this.notice = e.error?.message ?? 'Unable to reset password.'; } }); }
}
function passwordsMatch(control: AbstractControl): ValidationErrors | null { const password = control.get('password')?.value; const confirmPassword = control.get('confirmPassword')?.value; return password && confirmPassword && password !== confirmPassword ? { passwordMismatch: true } : null; }
